# -*- coding: utf-8 -*-
"""Numerical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkcBta0mYrweQusEyxAXBeaTnTMc41kc
"""

DB ={}
def load():
  try:
    f = open("db.txt", "r")
    for line in f:
      data = line.strip()
      data = line.split("#")
      # Ensure data has enough elements before accessing indices
      if len(data) == 6:
        DB[data[0]] = [data[1],int(data[2]),float(data[3]),float(data[4]),float(data[5])]
      else:
        print(f"Skipping malformed line in db.txt: {line.strip()}")
    print("Loading data ")
    f.close()
  except FileNotFoundError:
    print("db.txt not found. Starting with an empty database.")
  except Exception as e:
    print(f"An error occurred while loading data: {e}")


load()
def Display(sid):
    if sid in DB:
      print(DB[sid])
    else:
      print(f"Student ID {sid} not found")

def Insert(sid):
  if sid in DB:
    print(f"Student ID {sid} already exists")
  else:
    name = input("Enter student name: ")
    age = int(input("Enter student age: "))
    sc1 = float(input("Enter score 1: "))
    sc2 = float(input("Enter score 2: "))
    sc3 = float(input("Enter score 3: "))
    DB[sid] = [name,age,sc1,sc2,sc3]
    print(f"Student ID {sid} inserted")

def Update(sid):
  if sid in DB:
    tmp = DB[sid]
    print(f"Your old name is {tmp[0]}")
    ch = input("Do you want to change name ? (y/n): ")
    if ch.upper() == 'Y':
      name = input("Enter new name: ")
      tmp[0] = name
    print(f"Your old age is {tmp[1]}")
    ch = input("Do you want to change age ? (y/n): ")
    if ch.upper() == 'Y':
      age = int(input("Enter new age: "))
      tmp[1] = age
    print(f"Your old score 1 is {tmp[2]}")
    ch = input("Do you want to change score 1 ? (y/n): ")
    if ch.upper() == 'Y':
      sc1 = float(input("Enter new score 1: "))
      tmp[2] = sc1
    print(f"Your old score 2 is {tmp[3]}")
    ch = input("Do you want to change score 2 ? (y/n): ")
    if ch.upper() == 'Y':
      sc2 = float(input("Enter new score 2: "))
      tmp[3] = sc2
    print(f"Your old score 3 is {tmp[4]}")
    ch = input("Do you want to change score 3 ? (y/n): ")
    if ch.upper() == 'Y':
      sc3 = float(input("Enter new score 3: "))
      tmp[4] = sc3
    print(f"Student ID {sid} updated successfully!")
    DB[sid] = tmp
  else:
    print(f"Student ID {sid} not found for update.")

def Delete(sid):
  if sid in DB:
    del DB[sid]
    print(f"Student ID {sid} deleted successfully!")
  else:
    print(f"Student ID {sid} not found for deletion.")

def save():
  if len(DB) > 0:
    f = open("db.txt", "w")
    for key, value in DB.items():
      data = key+"#"+str(value[0])+"#"+str(value[1])+"#"+str(value[2])+"#"+str(value[3])+"#"+str(value[4])+"\n"
      f.write(data)
    f.close()
    print("Data saved successfully")
  else:
    print("No data to save")


def CalGrade(sid):
  if sid in DB:
    tmp = DB[sid]
    sc1 = tmp[2]
    sc2 = tmp[3]
    sc3 = tmp[4]
    avg = (sc1 + sc2 + sc3) / 3
    if avg >= 80:
      print("A")
    elif avg >= 70:
      print("B")
    elif avg >= 60:
      print("C")
    elif avg >= 50:
      print("D")
    else:
      print("F")
  else:
    print(f"Student ID {sid} not found for grade calculation.")

def Reg():
  print("-"*25)
  print("|\tRegistration\t|")
  print("-"*25)
  print("| 0. Exit\t\t|")
  print("| 1. Insert\t\t|")
  print("| 2. Update\t\t|")
  print("| 3. Delete\t\t|")
  print("| 4. Display\t\t|")
  print("| 5. Cal grade\t\t|")
  print("| 6. Save\t\t|")
  print("-"*25)
  try:
    choice = int(input("Enter your choice : "))
    return choice
  except ValueError:
    print("Invalid input. Please enter a number.")
    return -1
while True:
  ch = Reg()
  if ch == 1:
    print("Insert")
    sid = input("Enter student ID: ")
    Insert(sid)
  elif ch == 2:
    print("Update")
    sid = input("Enter student ID to update: ")
    Update(sid)
  elif ch == 3:
    print("Delete")
    sid = input("Enter student ID to delete: ")
    Delete(sid)
  elif ch == 4:
    try:
      student_id = input("Enter student : ")
      Display(student_id)
    except ValueError:
      print("Invalid ID format.")
  elif ch == 5:
    try:
      student_id = input("Enter student : ")
      CalGrade(student_id)
    except ValueError:
      print("Invalid ID format.")
  elif ch == 6:
    save()
    print("Save")
  elif ch == 0:
    print("Exiting Registration. Goodbye!")
    break
  elif ch == -1:
    pass
  else :
    print("Invalid choice")
  print("\n")

