# -*- coding: utf-8 -*-
"""matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aka6495wThqZp8uNow_5QO0VAD4W7RS7

# 1
"""

import numpy as np

A = np.array([[1, 2, 3], [2, -4, 5], [7, 8, 9], [-1, -2, -3]])
B = np.array([[7, 8, 9, 5], [-2, -3, -5, -7], [1, -1, 3, 5]])
C = np.array([[1, 2, 3], [4, 6, 7], [8, 9, 10], [2, 3, 4]])

if A.shape == C.shape:
    print(f"A + C = \n{A + C}")
else:
    print("Cannot add A and C.")

if A.shape[1] == B.shape[0]:
    AB = np.dot(A, B)
    print(f"AB = \n{AB}")
else:
    print("Cannot multiply A and B.")

if C.shape[1] == B.shape[0]:
    CB = np.dot(C, B)
    print(f"CB = \n{CB}")
else:
    print("Cannot multiply C and B.")

print(f"|AB| = {np.linalg.det(AB)}")

"""# 2"""

import numpy as np

def cr(A, B):
    det_a = np.linalg.det(A)
    if det_a == 0:
        raise ValueError("A is singular")
    num_variable = A.shape[1]
    solutions = np.zeros(num_variable)
    for i in range(num_variable):
        X_i = A.copy()
        X_i[:, i] = B
        det_X_i = np.linalg.det(X_i)
        solutions[i] = det_X_i / det_a
    return solutions


A = np.array([[0.3, 0.52, 1], [0.5, 1, 1], [0.1, 0.3, 0.5]])
B = np.array([-0.01, 0.67, -0.44])


result = cr(A, B)
print(result)