# -*- coding: utf-8 -*-
"""Numerical-fps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4y2UIoWJq9ylTHgy3OMoB83ofbXINhe
"""

def fps(a, b, f, esp):
  i, aOld, bOld, xOld, xNew, checkError = 0, 0, 0, 0, 0, 1000
  while checkError > esp:
    xNew = ((a*f(b))-(b*f(a)))/(f(b)-f(a))
    checkError = abs(xNew - xOld)/abs(xNew) * 100

    if f(a)*f(xNew) < 0:
      aOld = a
      bOld = b
      b = xNew
      xOld = b
    else:
      aOld = a
      bOld = b
      a = xNew
      xOld = a
    i += 1
    print(f"i ={i}")
    print(f"a ={aOld}, f(a) ={f(aOld)}")
    print(f"b ={bOld}, f(b) ={f(bOld)}")
    print(f"x ={xNew}, f(x) ={f(xNew)}, error ={checkError}")
    print("-"*50)
    if i == 10000:
      print("Cannot find root of equation!!!")
      checkError = 0
      break
  return xNew

a, b, esp = -1.5, 0.5, 0.5
f = lambda x: x**4 + 2*x**2 - x-3
root = fps(a, b, f, esp)
print(f"Root = {root}")